export const ProductItems = [
  {
    img: "/images/chicken-shawarma-0.jpg",
    titles: "CHICKEN SHAWARMA WITHOUT SAUSAGE",
    prices: "₦1,500",
    description: "Delicious chicken shawarma without sausage.",
    alt: "Chicken shawarma without sausage",
  },
  {
    img: "/images/chicken-shawarma-1.jpg",
    titles: "CHICKEN SHAWARMA WITH SAUSAGE",
    prices: "₦1,700",
    description: "Delicious chicken shawarma including one (1) sausage.",
    alt: "Chicken shawarma with sausage",
  },
  {
    img: "/images/chicken-shawarma-2.jpeg",
    titles: "CHICKEN SHAWARMA WITH DOUBLE SAUSAGE",
    prices: "₦1,900",
    description: "Delicious chicken shawarma with two(2) sausages.",
    alt: "Chicken shawarma with 2 sausages",
  },
  {
    img: "/images/beef-shawarma-0.jpg",
    titles: "BEEF SHAWARMA WITHOUT SAUSAGE",
    prices: "₦1,500",
    description: "Tasty beef shawarma without sausage.",
    alt: "Beef shawarma without sausage",
  },
  {
    img: "/images/beef-shawarma-1.jpg",
    titles: "BEEF SHAWARMA WITH SAUSAGE",
    prices: "₦1,700",
    description: "Tasty beef shawarma with one (1) sausage.",
    alt: "Beef shawarma with one sausage",
  },
  {
    img: "/images/beef-shawarma-2.jpg",
    titles: "BEEF SHAWARMA WITH DOUBLE SAUSAGE",
    prices: "₦1,900",
    description: "Tasty beef shawarma with double (2) sausages.",
    alt: "Beef shawarma with double sausage",
  },
  {
    img: "/images/chicken-burger.jpg",
    titles: "CHICKEN BURGER",
    prices: "₦1,500",
    description: "Mouth-watering chicken burger.",
    alt: "Chicken burger",
  },
  {
    img: "/images/chicken-burger-cheese.jpg",
    titles: "CHICKEN BURGER WITH CHEESE",
    prices: "₦1,700",
    description: "Mouth-watering chicken burger including cheese.",
    alt: "Chicken burger with cheese",
  },
  {
    img: "/images/beef-burger.jpg",
    titles: "BEEF BURGER",
    prices: "₦1,500",
    description: "Mouth-watering beef burger.",
    alt: "Beef burger",
  },
];
